### ISSUE TITLE
Use generic in Change.property() constructor

### ISSUE THREAD

**Issue by brun0xon** [rodydavis/undo#2]
Will it be better to use generics for enhanced static analysis?

**Comment by rodydavis** [comment]
I refactored it and will sync changes soon 👍🏼

**Comment by brun0xon** [comment]
Thanks👍

**Comment by rodydavis** [comment]
Fixed on 1.2.0

**Comment by rodydavis** [comment]
you can have a generic for each change with .add<T> or all changes with SimpleStack

**Comment by brun0xon** [comment]
Sounds good!
